steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/niveusgcp/cloud', '--build-arg', 'URL=${TAG_NAME}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/niveusgcp/cloud']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta','run','deploy','cloud','--set-env-vars','an_env_var="https://cloud-likeend-rdg7uidwzq-uc.a.run.app/"', '--image', 'gcr.io/niveusgcp/cloud', '--region', 'us-central1', '--quiet']
